#!/usr/bin/env python
import urllib2
from xml.etree.ElementTree import XML
import sys
import os

import kannel_util

def print_config():
    print "graph_title Kannel SMS queue size"
    print "graph_vlabel messages"
    print "graph_category kannel"
    print "graph_info This graph shows sizes of inbound and outbound SMS queues"

    print "in.label inbound"
    print "out.label outbound"

def print_data():
    status = kannel_util.get_status()

    print "in.value " + str(status['sms']['received']['queued'])
    print "out.value " + str(status['sms']['sent']['queued'])

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "config":
	print_config()
    else:
        print_data()
