#!/usr/bin/env python
import urllib2
from xml.etree.ElementTree import XML
import sys
import os

import kannel_util

def print_config():
    print "graph_title Kannel SMS store size"
    print "graph_vlabel messages"
    print "graph_category kannel"
    print "graph_info This graph shows size of SMS store"

    print "size.label size"

def print_data():
    status = kannel_util.get_status()

    print "size.value " + str(status['sms']['storesize'])

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "config":
	print_config()
    else:
        print_data()
