#!/usr/bin/env python
import urllib2
from xml.etree.ElementTree import XML
import sys
import os

import kannel_util

def print_config():
    print "graph_order in out"
    print "graph_title Kannel SMS throughput"
    print "graph_vlabel messages received (-) / sent (+) per ${graph_period}"
    print "graph_category kannel"
    print "graph_info This graph shows inbound and outbound SMS throughput"

    print "in.label received"
    print "in.type DERIVE"
    print "in.graph no"
    print "in.min 0"

    print "out.label message rate"
    print "out.type DERIVE"
    print "out.negative in"
    print "out.min 0"

def print_data():
    status = kannel_util.get_status()

    print "in.value " + str(status['sms']['received']['total'])
    print "out.value " + str(status['sms']['sent']['total'])

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "config":
	print_config()
    else:
        print_data()
